<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../MedulaOnKontrol.Application/MedulaOnKontrol.Application.csproj"/><FrameworkReference Include="Microsoft.AspNetCore.App"/><PackageReference Include="Dapper" Version="2.1.66"/><PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.9.1"/><PackageReference Include="BCrypt.Net-Next" Version="4.0.3"/><PackageReference Include="Polly.Core" Version="8.5.2"/><PackageReference Include="QuestPDF" Version="2025.7.4"/><PackageReference Include="ClosedXML" Version="0.104.2"/></ItemGroup></Project>
