DECLARE N NUMBER;
BEGIN
 SELECT COUNT(*) INTO N FROM ALL_USERS WHERE USERNAME='MEDULA_RUN';
 IF N>0 THEN
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON KURUM TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON KLINIK TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON KULLANICI TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON ROL TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON KULLANICI_ROL TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON KULLANICI_KLINIK_YETKI TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON HASTA TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON BASVURU TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON BASVURU_TANI TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON DONEM TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON FATURA TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON FATURA_KALEMI TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON BELGE TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON SUT_ISLEM TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON ICD10 TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON ISLEM_TANI_MATRIS TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON BIRLIKTE_FATURALANMAZ TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON PAKET_ICERIK TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON ISLEM_TEKRAR_LIMIT TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON BELGE_ZORUNLULUK TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON ILAC_MALZEME TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON KURAL TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON KURAL_CALISTIRMA TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON BULGU TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON BULGU_ISTISNA TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON RED_KAYDI TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON GONDERIM TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON DENETIM_ISI TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON DENETIM_ADAY TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT ON DENETIM_IZI TO MEDULA_RUN';
  EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON TOHUMLAMA TO MEDULA_RUN';
 END IF;
END;
/
