BEGIN
 EXECUTE IMMEDIATE 'CREATE INDEX IX_BULGU_CALISTIRMA ON BULGU(KURAL_CALISTIRMA_ID,SEVERITY,DURUM)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
 EXECUTE IMMEDIATE 'CREATE INDEX IX_CALISTIRMA_FATURA ON KURAL_CALISTIRMA(FATURA_ID,ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
