using System.Reflection;
using Dapper;
using MedulaOnKontrol.Application;
using MedulaOnKontrol.Domain;

namespace MedulaOnKontrol.Infrastructure.Persistence;

internal static class OracleColumnMappings
{
    private static readonly IReadOnlyDictionary<string, string> _legacyPropertyNames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Aciklama"] = "Description",
        ["Ad"] = "Name",
        ["AdSoyad"] = "AdSoyad",
        ["Adet"] = "Adet",
        ["Agirlik"] = "Agirlik",
        ["AgirlikNormalizeEt"] = "NormalizeWeights",
        ["AktifMi"] = "IsActive",
        ["AmeliyatMi"] = "AmeliyatMi",
        ["AnonimMi"] = "AnonimMi",
        ["AsamaSaniyeleri"] = "StageDurationsSeconds",
        ["AyniTakipFaturaSayisi"] = "AyniTakipFaturaSayisi",
        ["AzamiAdet"] = "AzamiAdet",
        ["Barkod"] = "Barkod",
        ["Basarisiz"] = "FailedCount",
        ["BasarisizGiris"] = "FailedLoginCount",
        ["Baslangic"] = "StartedAt",
        ["Basvuru"] = "Basvuru",
        ["BasvuruId"] = "BasvuruId",
        ["BasvuruTipi"] = "BasvuruTip",
        ["BasvuruTipiKisiti"] = "BasvuruTipiKisiti",
        ["BeklenenVersiyon"] = "ExpectedVersion",
        ["BelgeTarihi"] = "BelgeTarihi",
        ["BelgeTipi"] = "BelgeTip",
        ["BelgeZorunluluklari"] = "BelgeZorunluluklari",
        ["Belgeler"] = "Belgeler",
        ["BirimFiyat"] = "BirimFiyat",
        ["BirlikteFaturalanmaz"] = "BirlikteFaturalanmaz",
        ["Bitis"] = "FinishedAt",
        ["BulguId"] = "BulguId",
        ["Bulgular"] = "Bulgular",
        ["Carpanlar"] = "SeverityMultipliers",
        ["CikisTarihi"] = "CikisTarihi",
        ["Cinsiyet"] = "Cinsiyet",
        ["CinsiyetKisiti"] = "CinsiyetKisiti",
        ["DogruPozitif"] = "TruePositiveCount",
        ["DogumTarihi"] = "DogumTarihi",
        ["Donem"] = "Donem",
        ["DonemBaslangic"] = "DonemBaslangic",
        ["DonemKodu"] = "DonemKodu",
        ["DosyaReferansi"] = "DosyaReferansi",
        ["Durum"] = "Status",
        ["EImzaZorunluMu"] = "EImzaZorunluMu",
        ["EngelleyiciFatura"] = "EngelleyiciFatura",
        ["EngelleyiciSayisi"] = "EngelleyiciSayisi",
        ["EskiDegerJson"] = "PreviousValueJson",
        ["EslesenKuralKodu"] = "EslesenKuralKodu",
        ["EtkilenenTutar"] = "EtkilenenTutar",
        ["Fatura"] = "Fatura",
        ["FaturaId"] = "FaturaId",
        ["FaturaKalemiId"] = "FaturaKalemiId",
        ["FaturaNo"] = "FaturaNo",
        ["FaturaRevizyon"] = "FaturaRevizyon",
        ["FaturaSayisi"] = "FaturaSayisi",
        ["GecerlilikBaslangic"] = "GecerlilikBaslangic",
        ["GecerlilikBitis"] = "GecerlilikBitis",
        ["GecmisKalemler"] = "GecmisKalemler",
        ["Gerekce"] = "Gerekce",
        ["Gonderilen"] = "SubmittedCount",
        ["GonderimTarihi"] = "GonderimTarihi",
        ["GuncellemeTarihi"] = "UpdatedAt",
        ["GuncelleyenKullaniciId"] = "UpdatedByUserId",
        ["Hasta"] = "Hasta",
        ["HastaId"] = "HastaId",
        ["HastaNo"] = "HastaNo",
        ["Hata"] = "Error",
        ["HekimKodu"] = "HekimKodu",
        ["Icd10Kod"] = "Icd10Kod",
        ["Icd10KodOnegi"] = "Icd10KodOnegi",
        ["Ilaclar"] = "Ilaclar",
        ["Imza"] = "Signature",
        ["ImzaDurumu"] = "ImzaDurum",
        ["IpAdres"] = "IpAddress",
        ["Islem"] = "Operation",
        ["IslemTarihi"] = "IslemTarihi",
        ["IslemTipi"] = "OperationType",
        ["Islemler"] = "Islemler",
        ["Istisnalar"] = "Exceptions",
        ["KalemId"] = "KalemId",
        ["KalemTipi"] = "KalemTipi",
        ["Kalemler"] = "Kalemler",
        ["KapaliMi"] = "KapaliMi",
        ["KapanisTarihi"] = "KapanisTarihi",
        ["Kapsam"] = "Scope",
        ["KapsananIslemKodu"] = "KapsananIslemKodu",
        ["Kategori"] = "Category",
        ["KilitBitis"] = "LockedUntil",
        ["KimlikNo"] = "KimlikNo",
        ["Klinik"] = "Klinik",
        ["KlinikKodu"] = "KlinikKodu",
        ["Klinikler"] = "Klinikler",
        ["Kod"] = "Code",
        ["KontrolRevizyon"] = "KontrolRevizyon",
        ["KosulSaglandi"] = "IsConditionSatisfied",
        ["KullaniciAdi"] = "Username",
        ["KullaniciId"] = "UserId",
        ["KuralCalistirmaId"] = "KuralCalistirmaId",
        ["KuralKodu"] = "KuralKodu",
        ["KuralVersiyon"] = "KuralVersiyon",
        ["KurumId"] = "KurumId",
        ["Matris"] = "Matris",
        ["Mesaj"] = "Message",
        ["OdemeKisiti"] = "OdemeKisiti",
        ["OdemeKosuluSaglandiMi"] = "OdemeKosuluSaglandiMi",
        ["OlusturanKullaniciId"] = "CreatedByUserId",
        ["OlusturmaTarihi"] = "CreatedAt",
        ["OnaylayanKullaniciId"] = "OnaylayanKullaniciId",
        ["OnerilenAksiyon"] = "OnerilenAksiyon",
        ["OnlenenTahminiTutar"] = "OnlenenTahminiTutar",
        ["PaketKalemMi"] = "PaketKalemMi",
        ["PaketKodu"] = "PaketKodu",
        ["PaketMi"] = "PaketMi",
        ["Paketler"] = "Paketler",
        ["ParametreJson"] = "ParametersJson",
        ["ParolaHash"] = "PasswordHash",
        ["PeriyotGun"] = "PeriyotGun",
        ["ProvizyonNo"] = "ProvizyonNo",
        ["ProvizyonTarihi"] = "ProvizyonTarihi",
        ["Puan"] = "Puan",
        ["RaporZorunluMu"] = "RaporZorunluMu",
        ["RedAciklama"] = "RedAciklama",
        ["RedTarihi"] = "RedTarihi",
        ["RedTutar"] = "RedTutar",
        ["Reddedilen"] = "RejectedCount",
        ["Referans"] = "Reference",
        ["Revizyon"] = "Revision",
        ["RiskSkoru"] = "RiskSkoru",
        ["RisktekiTutar"] = "RisktekiTutar",
        ["Roller"] = "Roller",
        ["Sayfa"] = "PageNumber",
        ["SayfaBoyutu"] = "PageSize",
        ["SgkRedKodu"] = "SgkRedKodu",
        ["Simdi"] = "UtcNow",
        ["Siralama"] = "SortBy",
        ["SonCalistirmaId"] = "SonCalistirmaId",
        ["SonKontrolTarihi"] = "SonKontrolTarihi",
        ["SutIslemKodu"] = "SutIslemKodu",
        ["SutIslemKoduA"] = "SutIslemKoduA",
        ["SutIslemKoduB"] = "SutIslemKoduB",
        ["TakipNo"] = "TakipNo",
        ["Tamamlanan"] = "CompletedCount",
        ["TaniTipi"] = "TaniTip",
        ["Tanilar"] = "Tanilar",
        ["Tarih"] = "KayitTarihi",
        ["TekrarLimitleri"] = "TekrarLimitleri",
        ["Toplam"] = "TotalCount",
        ["ToplamTutar"] = "ToplamTutar",
        ["Tur"] = "Kind",
        ["Tutar"] = "Tutar",
        ["Varlik"] = "Varlik",
        ["VarlikAdi"] = "EntityName",
        ["VarlikId"] = "EntityId",
        ["Versiyon"] = "Version",
        ["YanlisNegatif"] = "FalseNegativeCount",
        ["YanlisPozitif"] = "FalsePositiveCount",
        ["YasMax"] = "YasMax",
        ["YasMin"] = "YasMin",
        ["YatisTarihi"] = "YatisTarihi",
        ["YeniDegerJson"] = "NewValueJson",
        ["Yon"] = "SortDirection",
        ["YururlukBaslangic"] = "YururlukBaslangic",
        ["YururlukBitis"] = "YururlukBitis",
        ["ZorunluMu"] = "ZorunluMu",
    };

    internal static void Configure()
    {
        var assemblies = new[] { typeof(Fatura).Assembly, typeof(ErisimKapsami).Assembly, typeof(MedulaRepository).Assembly };
        foreach (var type in assemblies.SelectMany(assembly => assembly.GetTypes()).Where(type => type.IsClass && !type.IsGenericType && type.GetConstructor(Type.EmptyTypes) != null))
        {
            SqlMapper.SetTypeMap(type, new CustomPropertyTypeMap(type, (mappedType, columnName) =>
            {
                var normalizedName = columnName.Replace("_", "", StringComparison.Ordinal);
                var propertyName = _legacyPropertyNames.GetValueOrDefault(normalizedName, normalizedName);
                return mappedType.GetProperties(BindingFlags.Instance | BindingFlags.Public).FirstOrDefault(property => string.Equals(property.Name, propertyName, StringComparison.OrdinalIgnoreCase))!;
            }));
        }
    }
}
