CREATE OR REPLACE PACKAGE PKG_ON_KONTROL AS
 PROCEDURE ADAYLARI_HAZIRLA(P_IS_ID NUMBER, P_DONEM NUMBER, P_KULLANICI_ID NUMBER, P_KURUM_ID NUMBER);
END;
/
CREATE OR REPLACE PACKAGE BODY PKG_ON_KONTROL AS
 PROCEDURE ADAYLARI_HAZIRLA(P_IS_ID NUMBER, P_DONEM NUMBER, P_KULLANICI_ID NUMBER, P_KURUM_ID NUMBER) IS
  TYPE T_IDS IS TABLE OF NUMBER;
  V_IDS T_IDS;
  CURSOR C_ADAY IS
   SELECT F.ID FROM FATURA F JOIN BASVURU B ON B.ID=F.BASVURU_ID
   WHERE F.DONEM=P_DONEM AND B.KURUM_ID=P_KURUM_ID AND F.DURUM IN (0,1,2,3)
   AND EXISTS (SELECT 1 FROM KULLANICI_KLINIK_YETKI Y JOIN KULLANICI U ON U.ID=Y.KULLANICI_ID
      WHERE Y.KULLANICI_ID=P_KULLANICI_ID AND U.AKTIF_MI=1 AND U.KURUM_ID=P_KURUM_ID
      AND Y.KURUM_ID=B.KURUM_ID AND Y.KLINIK_KODU=B.KLINIK_KODU)
   AND EXISTS (SELECT 1 FROM KURAL K WHERE K.AKTIF_MI=1 AND K.YURURLUK_BASLANGIC<=TO_DATE(TO_CHAR(P_DONEM)||'01','YYYYMMDD')
      AND (K.YURURLUK_BITIS IS NULL OR K.YURURLUK_BITIS>=TO_DATE(TO_CHAR(P_DONEM)||'01','YYYYMMDD')));
 BEGIN
  DELETE FROM DENETIM_ADAY WHERE IS_ID=P_IS_ID;
  OPEN C_ADAY;
  LOOP
   FETCH C_ADAY BULK COLLECT INTO V_IDS LIMIT 1000;
   EXIT WHEN V_IDS.COUNT=0;
   FORALL I IN 1..V_IDS.COUNT
    INSERT INTO DENETIM_ADAY(IS_ID,FATURA_ID,OLUSTURAN_KULLANICI_ID) VALUES(P_IS_ID,V_IDS(I),P_KULLANICI_ID);
  END LOOP;
  CLOSE C_ADAY;
 END;
END;
/

DECLARE N NUMBER;
BEGIN
 SELECT COUNT(*) INTO N FROM ALL_USERS WHERE USERNAME='MEDULA_RUN';
 IF N>0 THEN EXECUTE IMMEDIATE 'GRANT EXECUTE ON PKG_ON_KONTROL TO MEDULA_RUN'; END IF;
END;
/
