-- Read-only seed verification. No real patient data is distributed.
SELECT F.DONEM,COUNT(DISTINCT F.ID) FATURA_ADEDI,COUNT(K.ID) KALEM_ADEDI
FROM FATURA F JOIN BASVURU B ON B.ID=F.BASVURU_ID
JOIN FATURA_KALEMI K ON K.FATURA_ID=F.ID
WHERE B.KURUM_ID=1 AND F.FATURA_NO LIKE 'FT-%'
GROUP BY F.DONEM ORDER BY F.DONEM;

SELECT KATEGORI,COUNT(DISTINCT KURAL_KODU) KURAL_ADEDI FROM KURAL GROUP BY KATEGORI ORDER BY KATEGORI;

SELECT COUNT(*) ACIK_METIN_HASTA_SAYISI FROM HASTA
WHERE AD_SOYAD NOT LIKE 'v1:%' OR KIMLIK_NO NOT LIKE 'v1:%';

SELECT K.KATEGORI,COUNT(*) BULGU_ADEDI FROM BULGU B
JOIN KURAL K ON K.KURAL_KODU=B.KURAL_KODU AND K.VERSIYON=B.KURAL_VERSIYON
GROUP BY K.KATEGORI ORDER BY K.KATEGORI;
